//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3d_basic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3d_basic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;positions&quot;:[-1,1,-1,-1,-1,1,-1,-1,-1,-1,1,1,1,-1,1,1,1,1,1,-1,-1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,1,1,-1,1,-1]
        ///,&quot;normals&quot;:[-0.577,0.577,-0.577,-0.577,-0.577,0.577,-0.577,-0.577,-0.577,-0.577,0.577,0.577,0.577,-0.577,0.577,0.577,0.577,0.577,0.577,-0.577,-0.577,0.577,0.577,-0.577,-0.577,-0.577,-0.577,-0.577,-0.577,-0.577,-0.577,-0.577,0.577,-0.577,0.577,0.577,-0.577,0.577,-0.577,-0.577,-0.577,-0.577,-0.577,-0.577,-0.577,-0.577,0.577,0.577,-0.577,0.577,-0.577]
        ///,&quot;indice [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cube {
            get {
                return ResourceManager.GetString("cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;positions&quot;:[0.4688,0.2422,-0.7578,0.5,0.0938,-0.6875,0.5625,0.2422,-0.6719,-0.5,0.0938,-0.6875,-0.4688,0.2422,-0.7578,-0.5625,0.2422,-0.6719,0.5469,0.0547,-0.5781,0.625,0.2422,-0.5625,-0.5469,0.0547,-0.5781,-0.625,0.2422,-0.5625,0.3516,-0.0234,-0.6172,-0.3516,-0.0234,-0.6172,0.4375,0.1641,-0.7656,0.3516,0.0312,-0.7188,-0.3516,0.0312,-0.7188,-0.4375,0.1641,-0.7656,0.3516,0.1328,-0.7812
        ///,0.2031,0.0938,-0.7422,-0.2031,0.0938,-0.7422,-0.3516,0.1328,-0.7812,0.1562,0.0547,-0.6484,-0.1562,0.0547,-0.6484,0.140 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monkey {
            get {
                return ResourceManager.GetString("monkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;positions&quot;:[-0.591,0,-0.591,-0.4306,0,-0.4306,-0.643,0,-0.4002,-0.4002,0,-0.643,-0.2159,0,-0.451,-0.2021,0,-0.6761,0,0,-0.4583,0.2021,0,-0.6761,0,0,-0.6875,0.4002,0,-0.643,0.2159,0,-0.451,0.591,0,-0.591,0.4306,0,-0.4306,-0.451,0,-0.2159,-0.6761,0,-0.2021,-0.2256,0,-0.2256,0,0,-0.2292
        ///,0.2256,0,-0.2256,0.643,0,-0.4002,0.451,0,-0.2159,-0.4583,0,0,-0.6875,0,0,-0.2292,0,0,0,0,0,0.2292,0,0,0.6761,0,-0.2021,0.4583,0,0,-0.6761,0,0.2021,-0.451,0,0.2159,-0.2256,0,0.2256,0.2256,0,0.2256,0,0,0.2292,0.451,0,0.2159 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plane {
            get {
                return ResourceManager.GetString("plane", resourceCulture);
            }
        }
    }
}
